# Generated by Django 5.0.10 on 2024-12-28 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('wishlist_products', models.JSONField(default=list)),
                ('cart_products', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('seller', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('children', 'Children')], max_length=50)),
                ('description', models.TextField()),
                ('photo', models.URLField()),
                ('stock_quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('discount', models.FloatField()),
                ('keywords', models.JSONField(default=list)),
                ('sizes_list', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_email', models.EmailField(max_length=254, unique=True)),
                ('brand_name', models.CharField(max_length=255)),
                ('brand_email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
