# Generated by Django 5.0.10 on 2024-12-28 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('seller', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('children', 'Children')], max_length=50)),
                ('description', models.TextField()),
                ('photo', models.URLField()),
                ('stock_quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('discount', models.FloatField()),
                ('keywords', models.JSONField(default=list)),
                ('sizes_list', models.JSONField(default=list)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='cart_products',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='wishlist_products',
            field=models.JSONField(default=list),
        ),
    ]
