name: API Testing

on:
  workflow_run:
    workflows: ["Build and deploy Python app to Azure Web App - OuitfitOn"]
    types:
      - completed

jobs:
  test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2  

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run tests
        run: |
          python -m unittest discover -s . -p "test_*.py"
